### ISSUE TITLE
Set config flag not opening 

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#1249]
I just reinstalled windows 10. Didn't check whether this error was pre-existing but it throws this errors before updating to 32.80 also

Error in sys.excepthook:
Traceback (most recent call last):
  File "G:\BIBLE STUDY\App\UniqueBible\main.py", line 766, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "G:\BIBLE STUDY\App\UniqueBible\gui\MainWindow.py", line 2628, in moreConfigOptionsDialog
    self.configFlagsDialog = ConfigFlagsWindow(self)
  File "G:\BIBLE STUDY\App\UniqueBible\gui\ConfigFlagsWindow.py", line 23, in __init__
    self.setupUI()
  File "G:\BIBLE STUDY\App\UniqueBible\gui\ConfigFlagsWindow.py", line 47, in setupUI
    self.resetItems()
  File "G:\BIBLE STUDY\App\UniqueBible\gui\ConfigFlagsWindow.py", line 192, in resetItems
    self.data = self.getOptions()
  File "G:\BIBLE STUDY\App\UniqueBible\gui\ConfigFlagsWindow.py", line 89, in getOptions
    ("searchBibleIfCommandNotFound", config.searchBibleIfCommandNotFound, self.searchBibleIfCommandNotFoundChanged, True, config.thisTranslation["searchBibleIfCommandNotFound"]),
AttributeError: module 'config' has no attribute 'searchBibleIfCommandNotFound'

**Comment by eliranwong** [comment]
thanks for report, I will fix.

**Comment by eliranwong** [comment]
fixed. https://github.com/eliranwong/UniqueBible/commit/2547b1318e7c4948e69b50e09f9941603645e464
