### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by ShintoAW** [eliranwong/UniqueBible#1353]
I'm using Windows8.1Pro
Python 3.10.9

Got this error after installation

`PS F:\App\UniqueBible> python uba.py
PS F:\App\UniqueBible> pip tool updated!
Installing 'PySide6' ...
Module 'PySide6' is installed!
PySide6 is not found!  Trying to install 'PySide2' instead ...
Installing 'PySide2' ...
Module 'PySide2' is installed!
Installed!
Installed!
Installing 'chinese-english-lookup' ...
Module 'chinese-english-lookup' is installed!
Optional feature 'Chinese-to-English word definition' is not enabled.
Run 'pip3 install chinese-english-lookup' to install it first.
F:\App\UniqueBible\venv_Windows_3.10.9\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Cou
onv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning
Error in sys.excepthook:
Traceback (most recent call last):
  File "F:\App\UniqueBible\startup\share.py", line 63, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "F:\App\UniqueBible\main.py", line 147, in <module>
    from startup.guiQt import *
  File "F:\App\UniqueBible\venv_Windows_3.10.9\Lib\site-packages\shiboken2\files.dir\shibokensup
ne 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\App\UniqueBible\startup\guiQt.py", line 16, in <module>
    from gui.MainWindow import MainWindow
  File "F:\App\UniqueBible\venv_Windows_3.10.9\Lib\site-packages\shiboken2\files.dir\shibokensup
ne 142, in _import
    return original_import(name, *args, **kwargs)
  File "F:\App\UniqueBible\gui\MainWindow.py", line 12, in <module>
    from PySide6.QtGui import QIcon, QGuiApplication, QFont, QKeySequence, QColor, QPixmap, QCur
  File "F:\App\UniqueBible\venv_Windows_3.10.9\Lib\site-packages\shiboken2\files.dir\shibokensup
ne 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.`

**Comment by eliranwong** [comment]
sorry, I guess Windows 8 is not supported.  We tested the latest codes on Windows 11.
