### ISSUE TITLE
uba.py and UBA Bat file not working. 

### ISSUE THREAD

**Issue by RayReddingtonx** [eliranwong/UniqueBible#1354]
Uba py did nothing. The downloading started from activate_this.py from the downloaded folder of UBA. Then after the first run of the program, the two bat files appeared on the desktop. There the uba bat file did not open the program. Then I went through the Git clone process and downloaded the folder once again, but again the bat file doesnt work. I'm using win10 64. But the main.py is opening the program after showing this -: 
> .... Python\Python311\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
 

 But the uba.bat file gives these errors: 

> Desktop>powershell.exe -NoExit -Command "python 'C:\Users\ Downloads\UniqueBible-main\uba.py'"
> PS C:\Users\\Desktop> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "C:\Users\doads\UniqueBible-main\startup\share.py", line 63, in global_excepthook
>     print(traceback.format_exc())
>           ^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'traceback' object has no attribute 'format_exc'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "C:\Users\ s\UniqueBible-main\util\ShortcutUtil.py", line 8, in <module>
>     from PySide6.QtCore import Qt
> ModuleNotFoundError: No module named 'PySide6'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\C ads\UniqueBible-main\util\ShortcutUtil.py", line 12, in <module>
>     from qtpy.QtCore import Qt
> ModuleNotFoundError: No module named 'qtpy'
> 
> During handling of the above exception, another exception occurred:
 
 By the way, the python did not open initially, I had to edit and add the path of the folder in environment. I will delete the second folder created by git clone, and meanwhile use the program from the main.py file, The main.py sent to desktop shortcut is working, but if I close the error cmd window then the UBA program also closes. Plz reply with a perfect fix in next update or something. Meanwhile I will learn the program. 

Also, I need to ask if we can perform the advance syntax search, as it is done apps like logos using opentext.org database. You have the annoted bible features of linguistic tags to each words. If we can be allowed to search based on syntactic construction such as "article, participle, noun" or "adverb, noun, passive verb" will show all instances of those constructs; and also, if we can limit the criteria that "Law(accusative),with Subject:God" which give all instances of Law in accusative form with those words etc. https://support.logos.com/hc/en-us/articles/360017524912-Clause-Search

**Comment by RayReddingtonx** [comment]
I'm having great inconvenience in using UBA. A minor bug is when we decrease the font size from the shortcut, it only changes the font size of that window, but not others. The bigger issues are search results. I want to see search results in Greek as well as in English version, at least two, simultaneously, after searching for a Greek phrase. The English version shouldn't highlight it, of course, but all results should show in both languages. It will be great if you allow logos like search result option of "aligned" view of all phrases are shows aligned. I cannot see the results in the English to quickly check. The Marvel version results are shown along with the interlinear, but it's not convenient or easy to view many results quickly. Maybe the interlinear should also highlight the search phrase. I don't see multiple versions showing even in English search. I suggest an option should be, that if I give it a Greek phrase, then it should automatically search the LXX and Greek NT versions alone, not anything else, and then include the results from the selected English versions of the same verse. Searching is the most important feature in such app, it cannot be overstated.

When in the master control search box, I hit "search bible" nothing happens. But the search functions only when I hit enter; and sometimes the UBA closes or freezes for sometime after I hit enter or do it a couple of times.
