### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by orthodogz** [eliranwong/UniqueBible#1474]
On windows I got
 ```
C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe: can't open file 'C:\\Users\\User\\UniqueBible\\main.py': [Errno 2] No such file or directory after 
```
after start, I used pip installation method. also uniquebible require manual installtion of setuptools, openai, mistralai and groq pip packages to start

**Comment by otseng** [comment]
Can you try starting it with:
python -m uniquebible.main

https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows

**Comment by orthodogz** [comment]
> Can you try starting it with: python -m uniquebible.main
> 
> https://github.com/eliranwong/UniqueBible/wiki/Install-on-Windows

oh, I thought it was old method of installation, documentation is a little bit confusing. 
But with this method I got
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\Olga\Downloads\git\UniqueBible\uniquebible\startup\share.py", line 47, in global_excepthook
    print(traceback.format_exc())
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Olga\Downloads\git\UniqueBible\uniquebible\main.py", line 138, in <module>
    from uniquebible.startup.guiQt import *
  File "C:\Users\Olga\Downloads\git\UniqueBible\uniquebible\startup\guiQt.py", line 16, in <module>
    from uniquebible.gui.MainWindow import MainWindow
  File "C:\Users\Olga\Downloads\git\UniqueBible\uniquebible\gui\MainWindow.py", line 29, in <module>
    from uniquebible.gui.WorkSpace import Workspace
  File "C:\Users\Olga\Downloads\git\UniqueBible\uniquebible\gui\WorkSpace.py", line 4, in <module>
    import uniquebible.shortcut as sc
ModuleNotFoundError: No module named 'uniquebible.shortcut'
```

**Comment by orthodogz** [comment]
> Unzip this and add shortcut.py under the uniquebible folder and then retry. [shortcut.py.zip](https://github.com/user-attachments/files/17775500/shortcut.py.zip)

now it worked, thank you
