### ISSUE TITLE
issue with starter menu layout

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#263]
@otseng I switched to start menu layout from Focus > close UBA

cannot start now

Traceback (most recent call last):
  File "/home/eliranwong/UniqueBible/main.py", line 246, in <module>
    config.mainWindow = MainWindow()
  File "/home/eliranwong/UniqueBible/gui/MainWindow.py", line 108, in __init__
    self.setupMenuLayout(config.menuLayout)
  File "/home/eliranwong/UniqueBible/gui/MainWindow.py", line 188, in setupMenuLayout
    getattr(windowClass, 'setupToolBarStandardIconSize')(self)
  File "/home/eliranwong/UniqueBible/plugins/layout/Starter.py", line 103, in setupToolBarStandardIconSize
    self.addStandardIconButton("bar1_searchBible", "search.png", self.displaySearchBibleCommand, self.firstToolBar)
  File "/home/eliranwong/UniqueBible/gui/MainWindow.py", line 3040, in addStandardIconButton
    button.setFixedWidth(config.iconButtonWidth)
AttributeError: module 'config' has no attribute 'iconButtonWidth'****

can restart ONLY manually change menu option in config.py to "focus"

I think the issue is with the newly created "starter menu layout".

**Comment by eliranwong** [comment]
https://github.com/eliranwong/UniqueBible/commit/1960c3b43781984b5988e1f90056b62f9f17027d
