### ISSUE TITLE
after update coudn't start uba

### ISSUE THREAD

**Issue by onegladiator4u** [eliranwong/UniqueBible#613]
Installing missing module 'python-vlc' ...
Optional feature 'VLC Player' is not enabled.
Run 'pip3 install python-vlc' to install it first.
Traceback (most recent call last):
  File "C:\Users\John\Documents\UniqueBible\main.py", line 178, in <module>
    from gui.MainWindow import MainWindow
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\John\Documents\UniqueBible\gui\MainWindow.py", line 14, in <module>
    from gui.VlcPlayer import VlcPlayer
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\John\Documents\UniqueBible\gui\VlcPlayer.py", line 8, in <module>
    import vlc
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\John\Documents\UniqueBible\venv\lib\site-packages\vlc.py", line 210, in <module>
    dll, plugin_path  = find_lib()
  File "C:\Users\John\Documents\UniqueBible\venv\lib\site-packages\vlc.py", line 170, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\John\Documents\UniqueBible\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by otseng** [comment]
Can you try installing VLC?

https://www.videolan.org/vlc/

In the meantime, I'll add code to not break if VLC is not installed.

**Comment by onegladiator4u** [comment]
yup. done. now its

PS C:\Users\John\Documents\UniqueBible> Traceback (most recent call last):
  File "C:\Users\John\Documents\UniqueBible\main.py", line 378, in <module>
    config.mainWindow = MainWindow()
  File "C:\Users\John\Documents\UniqueBible\gui\MainWindow.py", line 120, in __init__
    self.setupMenuLayout(config.menuLayout)
  File "C:\Users\John\Documents\UniqueBible\gui\MainWindow.py", line 220, in setupMenuLayout
    getattr(windowClass, 'create_menu')(self)
  File "C:\Users\John\Documents\UniqueBible\gui\FocusMainWindow.py", line 257, in create_menu
    sc.openControlPanelTab6)):
AttributeError: module 'shortcut' has no attribute 'openControlPanelTab6'

**Comment by otseng** [comment]
Can you delete the shortcut.py file and restart?

**Comment by onegladiator4u** [comment]
tried deleting shortcut . didn't work.
i added `openControlPanelTab6 = ''`. but after running that line getting deleted automatically

**Comment by otseng** [comment]
I've tried to fix it in the latest update.  See if that fixes it.

**Comment by onegladiator4u** [comment]
how do i update it? i can't open the app

**Comment by otseng** [comment]
Can you replace util/ShortcutUtil.py with this file:

https://github.com/eliranwong/UniqueBible/blob/main/util/ShortcutUtil.py

**Comment by otseng** [comment]
Please run this:

python3 download.py util/ShortcutUtil.py

**Comment by otseng** [comment]
For reference, wiki here on downloading code if an update fails:
https://github.com/eliranwong/UniqueBible/wiki/Resolving-update-issues

**Comment by onegladiator4u** [comment]
it worked . i copied the code and replaced it.
now the app version is 25.66 and says its up to date .
but latest version is .69 right ?

**Comment by onegladiator4u** [comment]
> 
> 
> For reference, wiki here on downloading code if an update fails:
> https://github.com/eliranwong/UniqueBible/wiki/Resolving-update-issues

i didn't do it this way. is that a problem ?

**Comment by otseng** [comment]
> > For reference, wiki here on downloading code if an update fails:
> > https://github.com/eliranwong/UniqueBible/wiki/Resolving-update-issues
> 
> i didn't do it this way. is that a problem ?

You can do it any way.  The wiki way is just easier.

> it worked . i copied the code and replaced it.

Great.

> now the app version is 25.66 and says its up to date .
> but latest version is .69 right ?

Let me fix that...

**Comment by onegladiator4u** [comment]
ok

**Comment by otseng** [comment]
Give it a try now

**Comment by onegladiator4u** [comment]
![image](https://user-images.githubusercontent.com/48617390/124506507-6b2a8800-dde9-11eb-9e18-361db1d6dbf5.png)

**Comment by onegladiator4u** [comment]
when clicked on update it gave this
![image](https://user-images.githubusercontent.com/48617390/124506784-03287180-ddea-11eb-925f-e88a43208f54.png)
after that update finished . when i restarted it it's not running 
. tried powershell and got this error

`PS C:\Users\John\Documents\UniqueBible> Traceback (most recent call last):
  File "C:\Users\John\Documents\UniqueBible\main.py", line 181, in <module>
    from gui.MainWindow import MainWindow
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\John\Documents\UniqueBible\gui\MainWindow.py", line 37, in <module>
    from gui.MasterControl import MasterControl
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\John\Documents\UniqueBible\gui\MasterControl.py", line 5, in <module>
    from gui.MediaLauncher import MediaLauncher
  File "C:\Users\John\Documents\UniqueBible\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'gui.MediaLauncher'`

should i download the files as you mentioned ?

**Comment by onegladiator4u** [comment]
tried `python3 download.py gui.MediaLauncher`
but got an error 
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by otseng** [comment]
Added code to fix missing gui.MediaLauncher in 25.71

**Comment by onegladiator4u** [comment]
what should I do now?
