### ISSUE TITLE
App Does Not Start

### ISSUE THREAD

**Issue by PreacherBill** [eliranwong/UniqueBible#723]
The app was working the day before. Now on startup the app hangs up. I deleted the folder UniqueBible and cloned from github again. It still will not start. I love this program and am sure this is an error on my part, but how do I recover? Can I start fresh?

When starting from terminal I get the following message:

(base) bill@bill-Latitude-E7450:~$ python3 UniqueBible/uba.py
Setting up environment ...
(base) bill@bill-Latitude-E7450:~$ Traceback (most recent call last):
  File "/home/bill/UniqueBible/main.py", line 25, in <module>
    ConfigUtil.setup()
  File "/home/bill/UniqueBible/util/ConfigUtil.py", line 37, in setup
    config.booksFolder = os.path.join(config.marvelData, "books")
AttributeError: module 'config' has no attribute 'marvelData'

> (base) bill@bill-Latitude-E7450:~/UniqueBible$ python debug.py
==============================================================
Debugging Information
==============================================================
2021-08-03 07:41:15.492862

# Platform
Python=['3.9.1 (default, Dec 11 2020, 14:32:07) ', '[GCC 7.3.0]']
sysname=Linux
release=5.4.0-80-generic
version=#90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
machine=x86_64
platform=Linux-5.4.0-80-generic-x86_64-with-glibc2.31
platform=posix
platform=5.4.0-80-generic

# Locale
timezone=MDT-0600
defaultlocale=('en_US', 'UTF-8')
getlocale=en_US

# Version
UBA Version: 25.99

# Config
config.developer is undefined
config.enableCmd is undefined
config.theme is undefined
config.userLanguage is undefined
config.userLanguageInterface is undefined
config.menuLayout is undefined
config.theme is undefined
config.menuShortcuts is undefined
config.marvelData is undefined
config.qtMaterial is undefined
config.qtMaterialTheme is undefined
config.useLiteVerseParsing is undefined
config.startupMacro is undefined
config.enableMacros is undefined
config.useLiteVerseParsing is undefined
config.disableModulesUpdateCheck is undefined

# Marvel data
Could not get marvel data
(base) bill@bill-Latitude-E7450:~/UniqueBible$

**Comment by otseng** [comment]
Can you try running this and try again?

`python3 download.py util/ConfigUtil.py`

**Comment by PreacherBill** [comment]
It looked like it was going to work, but then this:

(base) bill@bill-Latitude-E7450:~/UniqueBible$ pip tool updated!
Installing missing module 'PySide2' ...
Installed!
Installing missing module 'qtpy' ...
Installed!
Installing missing module 'gdown' ...
Installed!
Installing missing module 'babel' ...
Installed!
Installing missing module 'html-text' ...
Installed!
Installing missing module 'beautifulsoup4' ...
Installed!
Installing missing module 'html5lib' ...
Installed!
Installing missing module 'mammoth' ...
Installed!
Installing missing module 'htmldocx' ...
Installed!
Installing missing module 'diff_match_patch' ...
Installed!
Installing missing module 'langdetect' ...
Installed!
Installing missing module 'pygithub' ...
Installed!
Installing missing module 'qt-material' ...
Installed!
Installing missing module 'telnetlib3' ...
Installed!
Installing missing module 'ibm-watson' ...
Installed!
Installing missing module 'qrcode' ...
Installed!
Installing missing module 'git+git://github.com/ojii/pymaging.git#egg=pymaging git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png' ...
Installed!
Installing missing module 'python-vlc' ...
Installed!
Downloading initial content 'images.sqlite' ...
Downloaded!
Unpacking ...
'images.sqlite' is installed!
Downloading initial content 'cCBSC.commentary' ...
Downloaded!
Unpacking ...
'cCBSC.commentary' is installed!
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "/home/bill/UniqueBible/main.py", line 385, in <module>
    setupMainWindow(availableGeometry)
  File "/home/bill/UniqueBible/main.py", line 216, in setupMainWindow
    config.mainWindow.checkMigration()
  File "/home/bill/UniqueBible/gui/MainWindow.py", line 399, in checkMigration
    biblesSqlite.migrateDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 804, in migrateDatabaseContent
    self.migratePlainDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 833, in migratePlainDatabaseContent
    if bible.checkTableExists('Verses'):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 1198, in checkTableExists
    self.cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,))
AttributeError: 'Bible' object has no attribute 'cursor'
Exception ignored in: <function Bible.__del__ at 0x7f6a53edba60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
(base) bill@bill-Latitude-E7450:~/UniqueBible$

**Comment by otseng** [comment]
Can you unzip this file and replace the util/ConfigUtil.py file?

[ConfigUtil.py.zip](https://github.com/eliranwong/UniqueBible/files/6925584/ConfigUtil.py.zip)

**Comment by PreacherBill** [comment]
I replaced the util/ConfigUtil.py file. Should I run python3 download.py util/ConfigUtil.py now or just python3 util/ConfigUtil.py ?

**Comment by otseng** [comment]
Try to start UBA now.

**Comment by PreacherBill** [comment]
No luck yet.

(base) bill@bill-Latitude-E7450:~/UniqueBible$ python3 uba.py
(base) bill@bill-Latitude-E7450:~/UniqueBible$ Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'
Traceback (most recent call last):
  File "/home/bill/UniqueBible/main.py", line 385, in <module>
    setupMainWindow(availableGeometry)
  File "/home/bill/UniqueBible/main.py", line 216, in setupMainWindow
    config.mainWindow.checkMigration()
  File "/home/bill/UniqueBible/gui/MainWindow.py", line 399, in checkMigration
    biblesSqlite.migrateDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 804, in migrateDatabaseContent
    self.migratePlainDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 833, in migratePlainDatabaseContent
    if bible.checkTableExists('Verses'):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 1198, in checkTableExists
    self.cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,))
AttributeError: 'Bible' object has no attribute 'cursor'
Exception ignored in: <function Bible.__del__ at 0x7fd7f2fc1a60>
Traceback (most recent call last):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 880, in __del__
    self.connection.commit()
AttributeError: 'NoneType' object has no attribute 'commit'

**Comment by otseng** [comment]
Added code to fix that problem.  Can you try redownloading and restart UBA again?

**Comment by PreacherBill** [comment]
I still got hung up.

(base) bill@bill-Latitude-E7450:~$ git clone https://github.com/eliranwong/UniqueBible
Cloning into 'UniqueBible'...
remote: Enumerating objects: 19092, done.
remote: Counting objects: 100% (6207/6207), done.
remote: Compressing objects: 100% (1824/1824), done.
remote: Total 19092 (delta 4435), reused 5629 (delta 3959), pack-reused 12885
Receiving objects: 100% (19092/19092), 372.14 MiB | 3.97 MiB/s, done.
Resolving deltas: 100% (11435/11435), done.
Updating files: 100% (4326/4326), done.
(base) bill@bill-Latitude-E7450:~$ cd UniqueBible
(base) bill@bill-Latitude-E7450:~/UniqueBible$ python3 uba.py
Setting up environment ...
(base) bill@bill-Latitude-E7450:~/UniqueBible$ pip tool updated!
Installing missing module 'PySide2' ...
Installed!
Installing missing module 'qtpy' ...
Installed!
Installing missing module 'gdown' ...
Installed!
Installing missing module 'babel' ...
(base) bill@bill-Latitude-E7450:~/UniqueBible$ Installed!
Installing missing module 'html-text' ...
Installed!
Installing missing module 'beautifulsoup4' ...
Installed!
Installing missing module 'html5lib' ...
Installed!
Installing missing module 'mammoth' ...
Installed!
Installing missing module 'htmldocx' ...
Installed!
Installing missing module 'diff_match_patch' ...
Installed!
Installing missing module 'langdetect' ...
Installed!
Installing missing module 'pygithub' ...
Installed!
Installing missing module 'qt-material' ...
Installed!
Installing missing module 'telnetlib3' ...
Installed!
Installing missing module 'ibm-watson' ...
Installed!
Installing missing module 'qrcode' ...
Installed!
Installing missing module 'git+git://github.com/ojii/pymaging.git#egg=pymaging git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png' ...
Installed!
Installing missing module 'python-vlc' ...
Installed!
Downloading initial content 'images.sqlite' ...
Downloaded!
Unpacking ...
'images.sqlite' is installed!
Downloading initial content 'cCBSC.commentary' ...
Downloaded!
Unpacking ...
'cCBSC.commentary' is installed!
Traceback (most recent call last):
  File "/home/bill/UniqueBible/main.py", line 385, in <module>
    setupMainWindow(availableGeometry)
  File "/home/bill/UniqueBible/main.py", line 216, in setupMainWindow
    config.mainWindow.checkMigration()
  File "/home/bill/UniqueBible/gui/MainWindow.py", line 399, in checkMigration
    biblesSqlite.migrateDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 804, in migrateDatabaseContent
    self.migratePlainDatabaseContent()
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 833, in migratePlainDatabaseContent
    if bible.checkTableExists('Verses'):
  File "/home/bill/UniqueBible/db/BiblesSqlite.py", line 1199, in checkTableExists
    self.cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,))
AttributeError: 'Bible' object has no attribute 'cursor'

**Comment by otseng** [comment]
Can you unzip this file and replace db/BiblesSqlite.py and then restart UBA?

[BiblesSqlite.py.zip](https://github.com/eliranwong/UniqueBible/files/6928426/BiblesSqlite.py.zip)

**Comment by PreacherBill** [comment]
That did the trick! Thank you so much! Blessings!
