### ISSUE TITLE
ModuleNotFoundError: no module name 'github'

### ISSUE THREAD

**Issue by bartonhammond** [eliranwong/UniqueBible#798]
Mac Big Sur 11.5.2
```
[bible]$ ./UniqueBible-main/uba.py 
Setting up environment ...

[bible]$ pip tool updated!
Installing missing module 'PySide2' ...
Installed!
/usr/local/lib/python3.7/site-packages/qtpy/__init__.py:222: RuntimeWarning: Selected binding "pyside2" could not be found, using "pyqt5"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Installing missing module 'html-text' ...
Optional feature 'Read html text' is not enabled.
Run 'pip3 install html-text' to install it first.
Installing missing module 'beautifulsoup4' ...
Optional feature 'HTML / XML Parser' is not enabled.
Run 'pip3 install beautifulsoup4' to install it first.
Installing missing module 'html5lib' ...
Optional feature 'HTML Library' is not enabled.
Run 'pip3 install html5lib' to install it first.
Installing missing module 'mammoth' ...
Optional feature 'Open DOCX file' is not enabled.
Run 'pip3 install mammoth' to install it first.
Installing missing module 'htmldocx' ...
Optional feature 'Convert HTML to DOCX' is not enabled.
Run 'pip3 install htmldocx' to install it first.
Installing missing module 'python-docx' ...
Optional feature 'Handle DOCX file' is not enabled.
Run 'pip3 install python-docx' to install it first.
Installing missing module 'diff_match_patch' ...
Optional feature 'Highlight Differences' is not enabled.
Run 'pip3 install diff_match_patch' to install it first.
Installing missing module 'langdetect' ...
Optional feature 'Detect Language' is not enabled.
Run 'pip3 install langdetect' to install it first.
Installing missing module 'pygithub' ...
Optional feature 'Github access' is not enabled.
Run 'pip3 install pygithub' to install it first.
Installing missing module 'qt-material' ...
Optional feature 'Qt Material Themes' is not enabled.
Run 'pip3 install qt-material' to install it first.
Installing missing module 'telnetlib3' ...
Optional feature 'Telnet Client and Server library' is not enabled.
Run 'pip3 install telnetlib3' to install it first.
Installing missing module 'ibm-watson' ...
Optional feature 'IBM-Watson Language Translator' is not enabled.
Run 'pip3 install ibm-watson' to install it first.
Installing missing module 'qrcode' ...
Optional feature 'QR Code' is not enabled.
Run 'pip3 install qrcode' to install it first.
Installing missing module 'git+git://github.com/ojii/pymaging.git#egg=pymaging git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png' ...
Optional feature 'Pure Python PNG' is not enabled.
Run 'pip3 install git+git://github.com/ojii/pymaging.git#egg=pymaging git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png' to install it first.
Installing missing module 'python-vlc' ...
Optional feature 'VLC Player' is not enabled.
Run 'pip3 install python-vlc' to install it first.
Text-to-speech feature is not enabled or supported on your device.
Traceback (most recent call last):
  File "/Users/bartonhammond/bible/UniqueBible-main/main.py", line 181, in <module>
    from gui.MainWindow import MainWindow
  File "/Users/bartonhammond/bible/UniqueBible-main/gui/MainWindow.py", line 16, in <module>
    from gui.LibraryCatalogDialog import LibraryCatalogDialog
  File "/Users/bartonhammond/bible/UniqueBible-main/gui/LibraryCatalogDialog.py", line 11, in <module>
    from util.CatalogUtil import CatalogUtil
  File "/Users/bartonhammond/bible/UniqueBible-main/util/CatalogUtil.py", line 5, in <module>
    from util.GithubUtil import GithubUtil
  File "/Users/bartonhammond/bible/UniqueBible-main/util/GithubUtil.py", line 2, in <module>
    from github import Github
ModuleNotFoundError: No module named 'github'
```

**Comment by bartonhammond** [comment]
Installed python3.8 and used `python3 ./UniqueBible-main/uba.py` and works fine!
