### ISSUE TITLE
Failed to read Error

### ISSUE THREAD

**Issue by GraceA555** [eliranwong/UniqueBible#861]
I installed windows 8.1, git and python3, but get an error when I try to install the program. I install it through Windows Powershell, it opens up DOS and the error comes on DOS. 
Installed python version-3.10.1-amd64

pip tool updated!
Installing missing module 'PySide2' ...
Installed!
C:\Users\Me\UniqueBible\venv\lib\site-packages\qtpy\__init__.py:201: RuntimeWarn
ing: Selected binding "pyside2" could not be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
Failed to read 'https://raw.githubusercontent.com/eliranwong/UniqueBible/main/Un
iqueBibleAppVersion.txt'.
Traceback (most recent call last):
  File "C:\Users\Me\UniqueBible\main.py", line 393, in <module>
    setupMainWindow(availableGeometry)
  File "C:\Users\Me\UniqueBible\main.py", line 209, in setupMainWindow
    config.mainWindow.manageControlPanel(config.showControlPanelOnStartup)
  File "C:\Users\Me\UniqueBible\gui\MainWindow.py", line 338, in manageControlPa
nel
    self.controlPanel = MasterControl(self, index, b, c, v, text)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 31, in __init__
    self.setupUI(b, c, v, text, initialTab)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 98, in setupUI
    mainLayout.addWidget(self.tabWidget(b, c, v, text, initialTab))
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 137, in tabWidget
    self.miscellaneousTab = MiscellaneousLauncher(self)
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 16, in __ini
t__
    self.setupUI()
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 25, in setup
UI
    rightLayout.addWidget(self.textToSpeechUtility())
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 79, in textT
oSpeechUtility
    self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + conf
ig.qttsSpeed * 150))
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by otseng** [comment]
What version of Python are you running?  Run `python -V`

**Comment by GraceA555** [comment]
python-3.10.1-amd64

**Comment by otseng** [comment]
Could you downgrade to 3.9?  3.10 is not currently supported.

**Comment by GraceA555** [comment]
Version 3.9.8 or 3.9.9?

**Comment by GraceA555** [comment]
Never mind the second was released 10 days later.

**Comment by GraceA555** [comment]
I installed 3.9.9 I got the same error, but it ran in Windows Powershell this time. It did not switch over to DOS.
Windows PowerShell

Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Users\Me> python .\UniqueBible\uba.py
PS C:\Users\Me> pip tool updated!
Installing missing module 'PySide2' ...
Installed!
C:\Users\Me\UniqueBible\venv\lib\site-packages\qtpy\__init__.py:201: RuntimeWarning: Selected binding "pyside2" could no
t be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
Traceback (most recent call last):
  File "C:\Users\Me\UniqueBible\main.py", line 393, in <module>
    setupMainWindow(availableGeometry)
  File "C:\Users\Me\UniqueBible\main.py", line 209, in setupMainWindow
    config.mainWindow.manageControlPanel(config.showControlPanelOnStartup)
  File "C:\Users\Me\UniqueBible\gui\MainWindow.py", line 338, in manageControlPanel
    self.controlPanel = MasterControl(self, index, b, c, v, text)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 31, in __init__
    self.setupUI(b, c, v, text, initialTab)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 98, in setupUI
    mainLayout.addWidget(self.tabWidget(b, c, v, text, initialTab))
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 137, in tabWidget
    self.miscellaneousTab = MiscellaneousLauncher(self)
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 16, in __init__
    self.setupUI()
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 25, in setupUI
    rightLayout.addWidget(self.textToSpeechUtility())
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 79, in textToSpeechUtility
    self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + config.qttsSpeed * 150))
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

Its waiting on some kind of input.

**Comment by otseng** [comment]
Can you try:
```
cd UniqueBible
python uba.py
```

**Comment by GraceA555** [comment]
I think it might be a python error. Many on google had a similar error to my last line, but the type was 'nonetype'. 

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Users\Me> cd UniqueBible
PS C:\Users\Me\UniqueBible> python uba.py
PS C:\Users\Me\UniqueBible> pip tool updated!
Installing missing module 'PySide2' ...
Installed!
C:\Users\Me\UniqueBible\venv\lib\site-packages\qtpy\__init__.py:201: RuntimeWarning: Selected binding "pyside2" could no
t be found, using "pyqt5"
  warnings.warn('Selected binding "{}" could not be found, '
Traceback (most recent call last):
  File "C:\Users\Me\UniqueBible\main.py", line 393, in <module>
    setupMainWindow(availableGeometry)
  File "C:\Users\Me\UniqueBible\main.py", line 209, in setupMainWindow
    config.mainWindow.manageControlPanel(config.showControlPanelOnStartup)
  File "C:\Users\Me\UniqueBible\gui\MainWindow.py", line 338, in manageControlPanel
    self.controlPanel = MasterControl(self, index, b, c, v, text)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 31, in __init__
    self.setupUI(b, c, v, text, initialTab)
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 98, in setupUI
    mainLayout.addWidget(self.tabWidget(b, c, v, text, initialTab))
  File "C:\Users\Me\UniqueBible\gui\MasterControl.py", line 137, in tabWidget
    self.miscellaneousTab = MiscellaneousLauncher(self)
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 16, in __init__
    self.setupUI()
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 25, in setupUI
    rightLayout.addWidget(self.textToSpeechUtility())
  File "C:\Users\Me\UniqueBible\gui\MiscellaneousLauncher.py", line 79, in textToSpeechUtility
    self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + config.qttsSpeed * 150))
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by otseng** [comment]
Two other things to try:

See if Python 3.8 works.

Comment out the offending lines by putting # at the very beginning.
```
#          self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + config.qttsSpeed * 150))
```

**Comment by GraceA555** [comment]
I don't understand what that means. do I copy that line if I get the error again?

**Comment by GraceA555** [comment]
Will you send me the version for esword. My email is gthang55@hotmail.com. Thanks

**Comment by GraceA555** [comment]
ok, I'll try those things. Thanks

**Comment by otseng** [comment]
> Will you send me the version for esword. My email is [gthang55@hotmail.com](mailto:gthang55@hotmail.com). Thanks

esword would be a completely different Bible study program.  You can download it from:
https://www.e-sword.net/
