### ISSUE TITLE
Add support to Arch Linux

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#883]
Add support to Arch Linux

will write installation notes

**Comment by eliranwong** [comment]
Error on installation, put notes here, follow up later:

...
'cCBSC.commentary' is installed!
Traceback (most recent call last):
  File "/config/UniqueBible/main.py", line 393, in <module>
    setupMainWindow(availableGeometry)
  File "/config/UniqueBible/main.py", line 209, in setupMainWindow
    config.mainWindow.manageControlPanel(config.showControlPanelOnStartup)
  File "/config/UniqueBible/gui/MainWindow.py", line 350, in manageControlPanel
    self.controlPanel = MasterControl(self, index, b, c, v, text)
  File "/config/UniqueBible/gui/MasterControl.py", line 31, in __init__
    self.setupUI(b, c, v, text, initialTab)
  File "/config/UniqueBible/gui/MasterControl.py", line 98, in setupUI
    mainLayout.addWidget(self.tabWidget(b, c, v, text, initialTab))
  File "/config/UniqueBible/gui/MasterControl.py", line 137, in tabWidget
    self.miscellaneousTab = MiscellaneousLauncher(self)
  File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 16, in __init__
    self.setupUI()
  File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 25, in setupUI
    rightLayout.addWidget(self.textToSpeechUtility())
  File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 79, in textToSpeechUtility
    self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + config.qttsSpeed * 150))
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by eliranwong** [comment]
> Error on installation, put notes here, follow up later:
> 
> ... 'cCBSC.commentary' is installed! Traceback (most recent call last): File "/config/UniqueBible/main.py", line 393, in setupMainWindow(availableGeometry) File "/config/UniqueBible/main.py", line 209, in setupMainWindow config.mainWindow.manageControlPanel(config.showControlPanelOnStartup) File "/config/UniqueBible/gui/MainWindow.py", line 350, in manageControlPanel self.controlPanel = MasterControl(self, index, b, c, v, text) File "/config/UniqueBible/gui/MasterControl.py", line 31, in **init** self.setupUI(b, c, v, text, initialTab) File "/config/UniqueBible/gui/MasterControl.py", line 98, in setupUI mainLayout.addWidget(self.tabWidget(b, c, v, text, initialTab)) File "/config/UniqueBible/gui/MasterControl.py", line 137, in tabWidget self.miscellaneousTab = MiscellaneousLauncher(self) File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 16, in **init** self.setupUI() File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 25, in setupUI rightLayout.addWidget(self.textToSpeechUtility()) File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 79, in textToSpeechUtility self.ttsSlider.setValue(config.espeakSpeed if config.espeak else (160 + config.qttsSpeed * 150)) TypeError: setValue(self, int): argument 1 has unexpected type 'float'

Fixed at https://github.com/eliranwong/UniqueBible/commit/ae489826cb4fcbf9f40df6ad2ada56683cb1dc7c

**Comment by eliranwong** [comment]
Added installation notes for Arch Linux user:

https://github.com/eliranwong/UniqueBible/wiki/Install-on-Linux#prepare-for-installation-arch-linux
