### ISSUE TITLE
Master Contarol Media Player tab does not update newly downloaded files unless UBA is restarted

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#889]
Master Contarol Media Player tab does not update newly downloaded files unless UBA is restartedac

it would be nice if the file list is updated after a music or video file is downloaded via youtube downloader.

**Comment by eliranwong** [comment]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/config/UniqueBible/main.py", line 451, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "/config/UniqueBible/util/CrossPlatform.py", line 175, in execPythonFile
    exec(code, globals())
  File "/config/UniqueBible/plugins/menu/Presentation.py", line 274, in <module>
    config.mainWindow.configurePresentationWindow = ConfigurePresentationWindow(config.mainWindow)
  File "/config/UniqueBible/plugins/menu/Presentation.py", line 25, in __init__
    self.setupUI()
  File "/config/UniqueBible/plugins/menu/Presentation.py", line 46, in setupUI
    self.fontsizeslider.setValue(config.presentationFontSize / 0.5)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/UniqueBible/gui/MiscellaneousLauncher.py", line 52, in <lambda>
    button.clicked.connect(lambda: self.parent.parent.runPlugin("Presentation"))
  File "/config/UniqueBible/gui/MainWindow.py", line 3622, in runPlugin
    self.crossPlatform.runPlugin(fileName)
  File "/config/UniqueBible/util/CrossPlatform.py", line 164, in runPlugin
    self.execPythonFile(script)
  File "/config/UniqueBible/util/CrossPlatform.py", line 177, in execPythonFile
    self.displayMessage("Failed to run '{0}'!".format(os.path.basename(script)))
AttributeError: 'CrossPlatform' object has no attribute 'displayMessage'
