### ISSUE TITLE
cannot open mini control with pyqt5

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#892]
Error in sys.excepthook:
Traceback (most recent call last):
  File "/config/UniqueBible/main.py", line 451, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "/config/UniqueBible/gui/MainWindow.py", line 373, in manageMiniControl
    self.miniControl = MiniControl(self, selectedTab)
  File "/config/UniqueBible/gui/MiniControl.py", line 38, in __init__
    self.resizeWindow(2 / 5, 1 / 3)
  File "/config/UniqueBible/gui/MiniControl.py", line 53, in resizeWindow
    self.resize(availableGeometry.width() * widthFactor, availableGeometry.height() * heightFactor)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'

**Comment by eliranwong** [comment]
fixed; https://github.com/eliranwong/UniqueBible/commit/afade802a46dc58592b2816ef452256480720833
