### ISSUE TITLE
error resizing main window under pyqt5

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#893]
Original exception was:
Traceback (most recent call last):
  File "/config/UniqueBible/gui/MainWindow.py", line 2371, in leftHalfScreenWidth
    self.resizeWindow(1 / 2, 1)
  File "/config/UniqueBible/gui/MainWindow.py", line 2382, in resizeWindow
    self.resize(availableGeometry.width() * widthFactor, availableGeometry.height() * heightFactor)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'

**Comment by eliranwong** [comment]
fixed; https://github.com/eliranwong/UniqueBible/commit/50b491898d3aa224a3ac2476ef4cdaecd350ffbe; https://github.com/eliranwong/UniqueBible/commit/d6f20e07f11e9bb43e8fb43cc28508a4d8a41187
