### ISSUE TITLE
failed to load qttheme with pyqt5

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#894]
Traceback (most recent call last):
  File "/config/UniqueBible/main.py", line 389, in <module>
    config.mainWindow = MainWindow()
  File "/config/UniqueBible/gui/MainWindow.py", line 125, in __init__
    self.setupMenuLayout(config.menuLayout)
  File "/config/UniqueBible/gui/MainWindow.py", line 230, in setupMenuLayout
    getattr(windowClass, 'setupToolBarStandardIconSize')(self)
  File "/config/UniqueBible/gui/FocusMainWindow.py", line 467, in setupToolBarStandardIconSize
    self.firstToolBar.setIconSize(QSize(config.iconButtonWidth / 2, config.iconButtonWidth / 2))
TypeError: arguments did not match any overloaded call:
  QSize(): too many arguments
  QSize(int, int): argument 1 has unexpected type 'float'
  QSize(QSize): argument 1 has unexpected type 'float'

**Comment by eliranwong** [comment]
fixed; https://github.com/eliranwong/UniqueBible/commit/c5923e1163bb5ba269f4905508fd2becf55a2ca1
