### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by darrelwright** [eliranwong/UniqueBible#914]
I used to be able to run "python3 uba.py docker" and UBA would start and run. Two updates ago things changed. Now when I run the same command I get the following error:

Traceback (most recent call last):
  File "/home/darrel/UniqueBible/main.py", line 406, in <module>
    config.mainWindow = MainWindow()
  File "/home/darrel/UniqueBible/gui/MainWindow.py", line 125, in __init__
    self.setupMenuLayout(config.menuLayout)
  File "/home/darrel/UniqueBible/gui/MainWindow.py", line 226, in setupMenuLayout
    getattr(windowClass, 'create_menu')(self)
  File "/home/darrel/UniqueBible/gui/FocusMainWindow.py", line 415, in create_menu
    with open("/defaults/menu.xml", "r") as fileObj:
FileNotFoundError: [Errno 2] No such file or directory: '/defaults/menu.xml'

How do I recover from that? If I run "python3 uba.py gui" then everything works fine.

**Comment by eliranwong** [comment]
this is not an issue at all.

the answer is simple.  the command "python3 uba.py docker" is not for running without docker.  The error shows that you are not running the docker Webtop version, which include latest features.  On webtop version, I seldom even need to type "python3 uba.py docker".  everything is well set on webtop version.

read for more information at: https://github.com/eliranwong/UniqueBible/wiki/Webtop-Version---RECOMMENDED

**Comment by eliranwong** [comment]
bty, errors occur on your side because UBA add an extra Apps menu on webtop version, which you are not running.

see a screenshot below, which shows the menu on webtop version.

![Uploading Screenshot 2022-02-23 at 09.39.28.png…]()

**Comment by darrelwright** [comment]
Hmmm. That means I must not have installed docker and the webtop 
correctly. Silly question - how do I uninstall and start over on docker 
and webtop because I did install (just not correctly I guess)?

**Comment by eliranwong** [comment]
as you use Linux, here is an example about installing webtop version on Linux.

**Comment by darrelwright** [comment]
Well, this frustrating. I install docker, then run "docker run 
hello-world" and it returns "Hello from Docker!" so that appears to work.

Next I run:

sudo docker run -d --name=uniquebibleapp --security-opt 
seccomp=unconfined -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -e 
SUBFOLDER=/ -e KEYBOARD=en-gb-qwerty -p 3000:3000 -v 
~/uniquebibleapp-webtop:/config -v 
/var/run/docker.sock:/var/run/docker.sock --shm-size="1gb" --restart 
unless-stopped eliranwong/uniquebibleapp
docker: Error response from daemon: Conflict. The container name 
"/uniquebibleapp" is already in use by container 
"620a500b9bea9cece179310e10b73510e1cdc50fa9a139d517ebcb45eae58a6e". You 
have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

I don't know how to remove that container. What do I do?

**Comment by eliranwong** [comment]
It seems very clear from the error message "The container name
"/uniquebibleapp" is already in use by container".  I think you have run the container before.  now you run it again.  normally, you just need to do it once.

to make sure you make sure you use the right one, remove the old one first, by running:

> sudo docker rm -f uniquebibleapp

before you run:

> sudo docker run -d --name=uniquebibleapp --security-opt
seccomp=unconfined -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -e
SUBFOLDER=/ -e KEYBOARD=en-gb-qwerty -p 3000:3000 -v
~/uniquebibleapp-webtop:/config -v
/var/run/docker.sock:/var/run/docker.sock --shm-size="1gb" --restart
unless-stopped eliranwong/uniquebibleapp

**Comment by eliranwong** [comment]
bty, if you are happy with the desktop version, you don't have to the webtop version.  webtop version takes larger storage.

**Comment by darrelwright** [comment]
I am happy with the desktop, but I want to get the webtop working (I 
have a lot of storage). My only issue is getting the webtop to install. 
I am trying to set up docker (running "sudo apt update & sudo apt 
dist-upgrade"). It runs part-way and appears to hang. Not sure how long 
to wait... This experience has not been as easy as you guys say it 
should be - or else I am a little dense.

**Comment by eliranwong** [comment]
simply remove the old image and put the new one in place will run, I think.

**Comment by darrelwright** [comment]
Unless I am missing something - not

**Comment by darrelwright** [comment]
This is frustrating! I have tried following the steps on this link and 
it does not work.

I don't know if it is because I am running Linux Mint 20.3. I keep 
failing. I have removed uniquebibleapp, then trying to follow steps for 
setting up docker. It never completes

**Comment by otseng** [comment]
I as well have not been able to get it to run on my Ubuntu.  But, I have gotten it to work on my Mac and Windows computers.

**Comment by darrelwright** [comment]
While I don't like hearing you having same issue, yet I'm pleased it's 
not just me!😂 Do we have any resolution? I will continue running the 
desktop until I hear something else.

**Comment by otseng** [comment]
I don't really have much of a need to get webtop running on Ubuntu.  Webtop would really be for people that are not able to get the desktop working.

**Comment by darrelwright** [comment]
What about the "new" things added to webtop?
