### ISSUE TITLE
another error running built-in media player

### ISSUE THREAD

**Issue by eliranwong** [eliranwong/UniqueBible#979]
Run the following command:

> vlc:::/home/eliranwong/uniquebibleapp-webtop/UniqueBible/audio/bibles/NET/default/1_1/NET_1_1_1.mp3

and get the errors below:

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/main.py", line 487, in global_excepthook
    print(traceback.format_exc())
AttributeError: 'traceback' object has no attribute 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/gui/MainWindow.py", line 2998, in textCommandEntered
    self.runTextCommand(newTextCommand, True, source)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/gui/MainWindow.py", line 3003, in runTextCommand
    self.passRunTextCommand(textCommand, addRecord, source, forceExecute)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/gui/MainWindow.py", line 3037, in passRunTextCommand
    view, content, dict = self.textCommandParser.parser(textCommand, source)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/util/TextCommandParser.py", line 776, in parser
    return self.interpreters[keyword][0](command, source)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/util/TextCommandParser.py", line 1487, in openVlcPlayer
    self.parent.vlcPlayer = VlcPlayer(self, filename)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/gui/VlcPlayer.py", line 29, in __init__
    self.instance = vlc.Instance()
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/venv2/lib/python3.9/site-packages/vlc.py", line 1814, in __new__
    return libvlc_new(len(args), args)
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/venv2/lib/python3.9/site-packages/vlc.py", line 4978, in libvlc_new
    _Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
  File "/home/eliranwong/uniquebibleapp-webtop/UniqueBible/venv2/lib/python3.9/site-packages/vlc.py", line 302, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'

**Comment by eliranwong** [comment]
seldom use vlc command, will take a look at this issue later
